### ISSUE TITLE
What is the configuration folder?

### ISSUE THREAD

**Issue by olivierpilotte** [slyeet03/spoify-tui#1]
```
Go to the spoify folder, and inside configure folder go to creds.yml.
```

What is the configuration folder?

**Comment by slyeet03** [comment]
It's the folder named configure, where you have to enter your Spotify API key. Without the API key, the application wouldnt work.

**Comment by olivierpilotte** [comment]
Yes, if I run from the code directory. If I install spoify using `cargo install spoify`, what would be the config directory?

**Comment by slyeet03** [comment]
Edit: I would suggest you to either update or do a fresh install, as i have updated it so it will ask your creds thru the terminal itself.

then it would be in your cargo bin directory, something like this:
'C:\Users\<your username>\.cargo\registry\src\index.crates.io-6f17d22bba15001f\spoify-0.1.2'
